import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import StoreProvider from "@/store/StoreProvider";

const noto = Noto_Sans({
  variable: "--font-noto_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Geography Geyser",
  description: "Generated by Geography Geyser",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.variable} antialiased font-noto`}>
        <StoreProvider>
          <Toaster position="top-right" richColors />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
